///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace PTB_Verification
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the PTB_VerificationRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.0")]
    [RepositoryFolder("53118fd7-41e4-4880-b7d1-86ef92933a2c")]
    public partial class PTB_VerificationRepository : RepoGenBaseFolder
    {
        static PTB_VerificationRepository instance = new PTB_VerificationRepository();
        PTB_VerificationRepositoryFolders.MeasureXUntitledAppFolder _measurexuntitled;
        PTB_VerificationRepositoryFolders.OpenMeasureXRoutineAppFolder _openmeasurexroutine;
        PTB_VerificationRepositoryFolders.MeasureXRunRoutineAppFolder _measurexrunroutine;
        PTB_VerificationRepositoryFolders.InspectionAppFolder _inspection;
        PTB_VerificationRepositoryFolders.SystemExitAppFolder _systemexit;
        PTB_VerificationRepositoryFolders.ExcelPTBResultsTableAppFolder _excelptbresultstable;
        PTB_VerificationRepositoryFolders.MXNTAppFolder _mxnt;
        PTB_VerificationRepositoryFolders.AboutMeasureXAppFolder _aboutmeasurex;

        /// <summary>
        /// Gets the singleton class instance representing the PTB_VerificationRepository element repository.
        /// </summary>
        [RepositoryFolder("53118fd7-41e4-4880-b7d1-86ef92933a2c")]
        public static PTB_VerificationRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public PTB_VerificationRepository() 
            : base("PTB_VerificationRepository", "/", null, 0, false, "53118fd7-41e4-4880-b7d1-86ef92933a2c", ".\\RepositoryImages\\PTB_VerificationRepository53118fd7.rximgres")
        {
            _measurexuntitled = new PTB_VerificationRepositoryFolders.MeasureXUntitledAppFolder(this);
            _openmeasurexroutine = new PTB_VerificationRepositoryFolders.OpenMeasureXRoutineAppFolder(this);
            _measurexrunroutine = new PTB_VerificationRepositoryFolders.MeasureXRunRoutineAppFolder(this);
            _inspection = new PTB_VerificationRepositoryFolders.InspectionAppFolder(this);
            _systemexit = new PTB_VerificationRepositoryFolders.SystemExitAppFolder(this);
            _excelptbresultstable = new PTB_VerificationRepositoryFolders.ExcelPTBResultsTableAppFolder(this);
            _mxnt = new PTB_VerificationRepositoryFolders.MXNTAppFolder(this);
            _aboutmeasurex = new PTB_VerificationRepositoryFolders.AboutMeasureXAppFolder(this);
        }

#region Variables

        string _SheetNumber = "";

        /// <summary>
        /// Gets or sets the value of variable SheetNumber.
        /// </summary>
        [TestVariable("4b05a976-13fd-4245-92ce-129146a59452")]
        public string SheetNumber
        {
            get { return _SheetNumber; }
            set { _SheetNumber = value; }
        }

        string _NewSheetName = "";

        /// <summary>
        /// Gets or sets the value of variable NewSheetName.
        /// </summary>
        [TestVariable("70cbc0b7-9f92-402d-8041-d16bae6b84be")]
        public string NewSheetName
        {
            get { return _NewSheetName; }
            set { _NewSheetName = value; }
        }

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("53118fd7-41e4-4880-b7d1-86ef92933a2c")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The MeasureXUntitled folder.
        /// </summary>
        [RepositoryFolder("a44b35bd-142b-4f42-9dbc-486a13818923")]
        public virtual PTB_VerificationRepositoryFolders.MeasureXUntitledAppFolder MeasureXUntitled
        {
            get { return _measurexuntitled; }
        }

        /// <summary>
        /// The OpenMeasureXRoutine folder.
        /// </summary>
        [RepositoryFolder("33b4a06d-a0e3-402d-9b58-955faf573b76")]
        public virtual PTB_VerificationRepositoryFolders.OpenMeasureXRoutineAppFolder OpenMeasureXRoutine
        {
            get { return _openmeasurexroutine; }
        }

        /// <summary>
        /// The MeasureXRunRoutine folder.
        /// </summary>
        [RepositoryFolder("01204b20-090d-40c6-b681-b9a9e0ba2fc1")]
        public virtual PTB_VerificationRepositoryFolders.MeasureXRunRoutineAppFolder MeasureXRunRoutine
        {
            get { return _measurexrunroutine; }
        }

        /// <summary>
        /// The Inspection folder.
        /// </summary>
        [RepositoryFolder("727188f7-5efb-4773-bbe6-0f9e3ea63c54")]
        public virtual PTB_VerificationRepositoryFolders.InspectionAppFolder Inspection
        {
            get { return _inspection; }
        }

        /// <summary>
        /// The SystemExit folder.
        /// </summary>
        [RepositoryFolder("6d1545bd-7854-4736-b790-bd896f6ec883")]
        public virtual PTB_VerificationRepositoryFolders.SystemExitAppFolder SystemExit
        {
            get { return _systemexit; }
        }

        /// <summary>
        /// The ExcelPTBResultsTable folder.
        /// </summary>
        [RepositoryFolder("f97dd3ec-10eb-4895-9691-8c0756d9eb88")]
        public virtual PTB_VerificationRepositoryFolders.ExcelPTBResultsTableAppFolder ExcelPTBResultsTable
        {
            get { return _excelptbresultstable; }
        }

        /// <summary>
        /// The MXNT folder.
        /// </summary>
        [RepositoryFolder("055b2bb7-7b00-41c2-b9f4-d9ab2b2177ac")]
        public virtual PTB_VerificationRepositoryFolders.MXNTAppFolder MXNT
        {
            get { return _mxnt; }
        }

        /// <summary>
        /// The AboutMeasureX folder.
        /// </summary>
        [RepositoryFolder("55bdea48-1aa7-4b42-bbed-26811b04a58e")]
        public virtual PTB_VerificationRepositoryFolders.AboutMeasureXAppFolder AboutMeasureX
        {
            get { return _aboutmeasurex; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.0")]
    public partial class PTB_VerificationRepositoryFolders
    {
        /// <summary>
        /// The MeasureXUntitledAppFolder folder.
        /// </summary>
        [RepositoryFolder("a44b35bd-142b-4f42-9dbc-486a13818923")]
        public partial class MeasureXUntitledAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _titlebarInfo;
            RepoItemInfo _helpInfo;

            /// <summary>
            /// Creates a new MeasureXUntitled  folder.
            /// </summary>
            public MeasureXUntitledAppFolder(RepoGenBaseFolder parentFolder) :
                    base("MeasureXUntitled", "/form[@title='Measure-X - [Untitled]']", parentFolder, 30000, null, true, "a44b35bd-142b-4f42-9dbc-486a13818923", "")
            {
                _titlebarInfo = new RepoItemInfo(this, "TitleBar", "titlebar[@accessiblerole='TitleBar']", 30000, null, "e7231432-10d2-492e-bbed-89258d101b12");
                _helpInfo = new RepoItemInfo(this, "Help", "?/?/menuitem[@accessiblename='Help']", 30000, null, "931f79bc-c3f5-4818-955c-0ee3656896f1");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("a44b35bd-142b-4f42-9dbc-486a13818923")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("a44b35bd-142b-4f42-9dbc-486a13818923")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The TitleBar item.
            /// </summary>
            [RepositoryItem("e7231432-10d2-492e-bbed-89258d101b12")]
            public virtual Ranorex.TitleBar TitleBar
            {
                get
                {
                    return _titlebarInfo.CreateAdapter<Ranorex.TitleBar>(true);
                }
            }

            /// <summary>
            /// The TitleBar item info.
            /// </summary>
            [RepositoryItemInfo("e7231432-10d2-492e-bbed-89258d101b12")]
            public virtual RepoItemInfo TitleBarInfo
            {
                get
                {
                    return _titlebarInfo;
                }
            }

            /// <summary>
            /// The Help item.
            /// </summary>
            [RepositoryItem("931f79bc-c3f5-4818-955c-0ee3656896f1")]
            public virtual Ranorex.MenuItem Help
            {
                get
                {
                    return _helpInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The Help item info.
            /// </summary>
            [RepositoryItemInfo("931f79bc-c3f5-4818-955c-0ee3656896f1")]
            public virtual RepoItemInfo HelpInfo
            {
                get
                {
                    return _helpInfo;
                }
            }
        }

        /// <summary>
        /// The OpenMeasureXRoutineAppFolder folder.
        /// </summary>
        [RepositoryFolder("33b4a06d-a0e3-402d-9b58-955faf573b76")]
        public partial class OpenMeasureXRoutineAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _filenamefieldInfo;

            /// <summary>
            /// Creates a new OpenMeasureXRoutine  folder.
            /// </summary>
            public OpenMeasureXRoutineAppFolder(RepoGenBaseFolder parentFolder) :
                    base("OpenMeasureXRoutine", "/form[@title='Open Measure-X Routine']", parentFolder, 30000, null, true, "33b4a06d-a0e3-402d-9b58-955faf573b76", "")
            {
                _filenamefieldInfo = new RepoItemInfo(this, "FileNameField", "?/?/text[@controlid='1148']", 30000, null, "d0ab019f-02e8-4bc8-bcc9-ee75a7f8832f");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("33b4a06d-a0e3-402d-9b58-955faf573b76")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("33b4a06d-a0e3-402d-9b58-955faf573b76")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The FileNameField item.
            /// </summary>
            [RepositoryItem("d0ab019f-02e8-4bc8-bcc9-ee75a7f8832f")]
            public virtual Ranorex.Text FileNameField
            {
                get
                {
                    return _filenamefieldInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The FileNameField item info.
            /// </summary>
            [RepositoryItemInfo("d0ab019f-02e8-4bc8-bcc9-ee75a7f8832f")]
            public virtual RepoItemInfo FileNameFieldInfo
            {
                get
                {
                    return _filenamefieldInfo;
                }
            }
        }

        /// <summary>
        /// The MeasureXRunRoutineAppFolder folder.
        /// </summary>
        [RepositoryFolder("01204b20-090d-40c6-b681-b9a9e0ba2fc1")]
        public partial class MeasureXRunRoutineAppFolder : RepoGenBaseFolder
        {
            //RepoItemInfo _titlebarwithloadedroutineInfo;    // I AM GOING TO USE ( _titlebarInfo)
            RepoItemInfo _runroutinebuttonokInfo;

            /// <summary>
            /// Creates a new MeasureXRunRoutine  folder.
            /// </summary>
            public MeasureXRunRoutineAppFolder(RepoGenBaseFolder parentFolder) : base("MeasureXDJoroGITAutomationMXA", "/form[@title~'^Measure-X\\ -\\ \\[D:\\\\Joro\\\\GIT_']", parentFolder, 30000, null, true, "01204b20-090d-40c6-b681-b9a9e0ba2fc1", "")
            {
                // _titlebarwithloadedroutineInfo = new RepoItemInfo(this, "MeasureXDJoroGITAutomationMXA", "titlebar[@accessiblerole='TitleBar']", 30000, null, "e58ae3a7-91c5-4fb0-8170-3928eb3314c8"); // I AM GOING TO USE ( _titlebarInfo)
                _runroutinebuttonokInfo = new RepoItemInfo(this, "RunRoutineButtonOK", "?/?/form[@controlid='65280']//container[@controlid='59648']/button[@text='&OK']", 30000, null, "47652d63-acdd-4fb2-9e9c-86ed7c50de0c");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("01204b20-090d-40c6-b681-b9a9e0ba2fc1")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("01204b20-090d-40c6-b681-b9a9e0ba2fc1")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The TitleBarWithLoadedRoutine item.
            /// </summary>
            [RepositoryItem("e58ae3a7-91c5-4fb0-8170-3928eb3314c8")]
            //public virtual Ranorex.TitleBar TitleBarWithLoadedRoutine
            //{
            //    get
            //    {
            //        return _titlebarwithloadedroutineInfo.CreateAdapter<Ranorex.TitleBar>(true);
            //    }
            //}

            // THIS CODE WORKS FINE , BUT I WANT TO USE ONE AND THE SAME CODE FOR THE THREE OPERATIONS (WE HAVE THREE CLICKS ON THE TITLEBAR). // I AM GOING TO USE ( _titlebarInfo)

            /// <summary>
            /// The TitleBarWithLoadedRoutine item info.
            /// </summary>
            [RepositoryItemInfo("e58ae3a7-91c5-4fb0-8170-3928eb3314c8")]
            //public virtual RepoItemInfo TitleBarWithLoadedRoutineInfo
            //{
            //    get
            //    {
            //        return _titlebarwithloadedroutineInfo;
            //    }
            //}

            // THIS CODE WORKS FINE , BUT I WANT TO USE ONE AND THE SAME CODE FOR THE THREE OPERATIONS (WE HAVE THREE CLICKS ON THE TITLEBAR). // I AM GOING TO USE ( _titlebarInfo)

            /// <summary>
            /// The RunRoutineButtonOK item.
            /// </summary>
            //[RepositoryItem("47652d63-acdd-4fb2-9e9c-86ed7c50de0c")]
            public virtual Ranorex.Button RunRoutineButtonOK
            {
                get
                {
                    return _runroutinebuttonokInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The RunRoutineButtonOK item info.
            /// </summary>
            [RepositoryItemInfo("47652d63-acdd-4fb2-9e9c-86ed7c50de0c")]
            public virtual RepoItemInfo RunRoutineButtonOKInfo
            {
                get
                {
                    return _runroutinebuttonokInfo;
                }
            }
        }

        /// <summary>
        /// The InspectionAppFolder folder.
        /// </summary>
        [RepositoryFolder("727188f7-5efb-4773-bbe6-0f9e3ea63c54")]
        public partial class InspectionAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _endofrunbuttonokInfo;

            /// <summary>
            /// Creates a new Inspection  folder.
            /// </summary>
            public InspectionAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Inspection", "/form[@title='Inspection']", parentFolder, 30000, null, true, "727188f7-5efb-4773-bbe6-0f9e3ea63c54", "")
            {
                _endofrunbuttonokInfo = new RepoItemInfo(this, "EndOfRunButtonOK", "button[@text='&OK']", 30000, null, "3c7e991d-cef4-467e-905d-fdb8e48b6bea");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("727188f7-5efb-4773-bbe6-0f9e3ea63c54")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("727188f7-5efb-4773-bbe6-0f9e3ea63c54")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The EndOfRunButtonOK item.
            /// </summary>
            [RepositoryItem("3c7e991d-cef4-467e-905d-fdb8e48b6bea")]
            public virtual Ranorex.Button EndOfRunButtonOK
            {
                get
                {
                    return _endofrunbuttonokInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The EndOfRunButtonOK item info.
            /// </summary>
            [RepositoryItemInfo("3c7e991d-cef4-467e-905d-fdb8e48b6bea")]
            public virtual RepoItemInfo EndOfRunButtonOKInfo
            {
                get
                {
                    return _endofrunbuttonokInfo;
                }
            }
        }

        /// <summary>
        /// The SystemExitAppFolder folder.
        /// </summary>
        [RepositoryFolder("6d1545bd-7854-4736-b790-bd896f6ec883")]
        public partial class SystemExitAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _exitbuttonokInfo;

            /// <summary>
            /// Creates a new SystemExit  folder.
            /// </summary>
            public SystemExitAppFolder(RepoGenBaseFolder parentFolder) :
                    base("SystemExit", "/form[@title='System Exit']", parentFolder, 30000, null, true, "6d1545bd-7854-4736-b790-bd896f6ec883", "")
            {
                _exitbuttonokInfo = new RepoItemInfo(this, "ExitButtonOK", "button[@text='&OK']", 30000, null, "c9fd657c-aeb5-4ce1-901d-9bfa8b9a6fc8");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("6d1545bd-7854-4736-b790-bd896f6ec883")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("6d1545bd-7854-4736-b790-bd896f6ec883")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ExitButtonOK item.
            /// </summary>
            [RepositoryItem("c9fd657c-aeb5-4ce1-901d-9bfa8b9a6fc8")]
            public virtual Ranorex.Button ExitButtonOK
            {
                get
                {
                    return _exitbuttonokInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ExitButtonOK item info.
            /// </summary>
            [RepositoryItemInfo("c9fd657c-aeb5-4ce1-901d-9bfa8b9a6fc8")]
            public virtual RepoItemInfo ExitButtonOKInfo
            {
                get
                {
                    return _exitbuttonokInfo;
                }
            }
        }

        /// <summary>
        /// The ExcelPTBResultsTableAppFolder folder.
        /// </summary>
        [RepositoryFolder("f97dd3ec-10eb-4895-9691-8c0756d9eb88")]
        public partial class ExcelPTBResultsTableAppFolder : RepoGenBaseFolder
        {
            PTB_VerificationRepositoryFolders.ResultsFolder _results;
            RepoItemInfo _filenamefieldforresults_txtInfo;
            RepoItemInfo _nextInfo;
            RepoItemInfo _finishInfo;
            

            static public RepoItemInfo _cellb4Info;
            static public RepoItemInfo _d218Info;
            static public RepoItemInfo _cellm4Info;

            /// <summary>
            /// Creates a new ExcelPTBResultsTable  folder.
            /// </summary>
            public ExcelPTBResultsTableAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ExcelPTBResultsTable", "/form[@processname='EXCEL']", parentFolder, 30000, null, true, "f97dd3ec-10eb-4895-9691-8c0756d9eb88", "")
            {
                _results = new PTB_VerificationRepositoryFolders.ResultsFolder(this);
                _filenamefieldforresults_txtInfo = new RepoItemInfo(this, "FileNameFieldForResults_txt", "combobox[@controlid='1148']", 2000, null, "3e5bbd46-b9aa-45bc-9b8c-aab30cbc7331");
                _nextInfo = new RepoItemInfo(this, "Next", "button[@accessiblename='Next >']", 1000, null, "fdde601f-1c25-40ab-94bb-a0647864b191");
                _finishInfo = new RepoItemInfo(this, "Finish", "button[@accessiblename='Finish']", 1000, null, "f78acae7-1916-41fa-ba5b-cea64448f532");
                _cellb4Info = new RepoItemInfo(this, "CellB4", ".//table[@name='5.2.112 (2)']/row[@index='4']/cell[@address='B4']", 30000, null, "3d3f27aa-5aeb-422f-926b-e037164b164e");
                _d218Info = new RepoItemInfo(this, "D218", ".//table[@name='5.2.112 (2)']/row[@index='218']/cell[@address='D218']", 30000, null, "c06a7e2e-8a6f-4430-87ec-47d8ffd01851");
                _cellm4Info = new RepoItemInfo(this, "CellM4", ".//table[@name='5.2.111']/row[@index='4']/cell[@address='M4']", 30000, null, "445b9093-3bf0-4392-a23c-a9e20bdbb832");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("f97dd3ec-10eb-4895-9691-8c0756d9eb88")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("f97dd3ec-10eb-4895-9691-8c0756d9eb88")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The FileNameFieldForResults_txt item.
            /// </summary>
            [RepositoryItem("3e5bbd46-b9aa-45bc-9b8c-aab30cbc7331")]
            public virtual Ranorex.ComboBox FileNameFieldForResults_txt
            {
                get
                {
                    return _filenamefieldforresults_txtInfo.CreateAdapter<Ranorex.ComboBox>(true);
                }
            }

            /// <summary>
            /// The FileNameFieldForResults_txt item info.
            /// </summary>
            [RepositoryItemInfo("3e5bbd46-b9aa-45bc-9b8c-aab30cbc7331")]
            public virtual RepoItemInfo FileNameFieldForResults_txtInfo
            {
                get
                {
                    return _filenamefieldforresults_txtInfo;
                }
            }

            /// <summary>
            /// The Next item.
            /// </summary>
            [RepositoryItem("fdde601f-1c25-40ab-94bb-a0647864b191")]
            public virtual Ranorex.Button Next
            {
                get
                {
                    return _nextInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Next item info.
            /// </summary>
            [RepositoryItemInfo("fdde601f-1c25-40ab-94bb-a0647864b191")]
            public virtual RepoItemInfo NextInfo
            {
                get
                {
                    return _nextInfo;
                }
            }

            /// <summary>
            /// The Finish item.
            /// </summary>
            [RepositoryItem("f78acae7-1916-41fa-ba5b-cea64448f532")]
            public virtual Ranorex.Button Finish
            {
                get
                {
                    return _finishInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Finish item info.
            /// </summary>
            [RepositoryItemInfo("f78acae7-1916-41fa-ba5b-cea64448f532")]
            public virtual RepoItemInfo FinishInfo
            {
                get
                {
                    return _finishInfo;
                }
            }

            /// <summary>
            /// The CellB4 item.
            /// </summary>
            [RepositoryItem("3d3f27aa-5aeb-422f-926b-e037164b164e")]
            public virtual Ranorex.Cell CellB4
            {
                get
                {
                    return _cellb4Info.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The CellB4 item info.
            /// </summary>
            [RepositoryItemInfo("3d3f27aa-5aeb-422f-926b-e037164b164e")]
            public virtual RepoItemInfo CellB4Info
            {
                get
                {
                    return _cellb4Info;
                }
            }

            /// <summary>
            /// The D218 item.
            /// </summary>
            [RepositoryItem("c06a7e2e-8a6f-4430-87ec-47d8ffd01851")]
            public virtual Ranorex.Cell D218
            {
                get
                {
                    return _d218Info.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The D218 item info.
            /// </summary>
            [RepositoryItemInfo("c06a7e2e-8a6f-4430-87ec-47d8ffd01851")]
            public virtual RepoItemInfo D218Info
            {
                get
                {
                    return _d218Info;
                }
            }

            /// <summary>
            /// The CellM4 item.
            /// </summary>
            [RepositoryItem("445b9093-3bf0-4392-a23c-a9e20bdbb832")]
            public virtual Ranorex.Cell CellM4
            {
                get
                {
                    return _cellm4Info.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The CellM4 item info.
            /// </summary>
            [RepositoryItemInfo("445b9093-3bf0-4392-a23c-a9e20bdbb832")]
            public virtual RepoItemInfo CellM4Info
            {
                get
                {
                    return _cellm4Info;
                }
            }

            /// <summary>
            /// The Results folder.
            /// </summary>
            [RepositoryFolder("d3231765-f184-4a56-a2cb-4097399ee958")]
            public virtual PTB_VerificationRepositoryFolders.ResultsFolder Results
            {
                get { return _results; }
            }
        }

        /// <summary>
        /// The ResultsFolder folder.
        /// </summary>
        [RepositoryFolder("d3231765-f184-4a56-a2cb-4097399ee958")]
        public partial class ResultsFolder : RepoGenBaseFolder
        {
            RepoItemInfo _d217Info;
            RepoItemInfo _cellb3Info;
            RepoItemInfo _row3Info;

            /// <summary>
            /// Creates a new Results  folder.
            /// </summary>
            public ResultsFolder(RepoGenBaseFolder parentFolder) :
                    base("Results", ".//table[@name='results']", parentFolder, 30000, null, false, "d3231765-f184-4a56-a2cb-4097399ee958", "")
            {
                _d217Info = new RepoItemInfo(this, "D217", "row[@index='217']/cell[@address='D217']", 30000, null, "dee7476a-ca6d-4df4-9403-8eac5dd47a3d");
                _cellb3Info = new RepoItemInfo(this, "CellB3", "row[@index='3']/cell[@address='B3']", 30000, null, "dade29cf-8668-4183-91d6-cc2c6ff2ba7c");
                _row3Info = new RepoItemInfo(this, "Row3", "row[@index='3']", 30000, null, "7733f50f-4355-428a-887e-a3cd6aa77c5c");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("d3231765-f184-4a56-a2cb-4097399ee958")]
            public virtual Ranorex.Table Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Table>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("d3231765-f184-4a56-a2cb-4097399ee958")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The D217 item.
            /// </summary>
            [RepositoryItem("dee7476a-ca6d-4df4-9403-8eac5dd47a3d")]
            public virtual Ranorex.Cell D217
            {
                get
                {
                    return _d217Info.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The D217 item info.
            /// </summary>
            [RepositoryItemInfo("dee7476a-ca6d-4df4-9403-8eac5dd47a3d")]
            public virtual RepoItemInfo D217Info
            {
                get
                {
                    return _d217Info;
                }
            }

            /// <summary>
            /// The CellB3 item.
            /// </summary>
            [RepositoryItem("dade29cf-8668-4183-91d6-cc2c6ff2ba7c")]
            public virtual Ranorex.Cell CellB3
            {
                get
                {
                    return _cellb3Info.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The CellB3 item info.
            /// </summary>
            [RepositoryItemInfo("dade29cf-8668-4183-91d6-cc2c6ff2ba7c")]
            public virtual RepoItemInfo CellB3Info
            {
                get
                {
                    return _cellb3Info;
                }
            }

            /// <summary>
            /// The Row3 item.
            /// </summary>
            [RepositoryItem("7733f50f-4355-428a-887e-a3cd6aa77c5c")]
            public virtual Ranorex.Row Row3
            {
                get
                {
                    return _row3Info.CreateAdapter<Ranorex.Row>(true);
                }
            }

            /// <summary>
            /// The Row3 item info.
            /// </summary>
            [RepositoryItemInfo("7733f50f-4355-428a-887e-a3cd6aa77c5c")]
            public virtual RepoItemInfo Row3Info
            {
                get
                {
                    return _row3Info;
                }
            }
        }

        /// <summary>
        /// The MXNTAppFolder folder.
        /// </summary>
        [RepositoryFolder("055b2bb7-7b00-41c2-b9f4-d9ab2b2177ac")]
        public partial class MXNTAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _aboutmeasurexInfo;

            /// <summary>
            /// Creates a new MXNT  folder.
            /// </summary>
            public MXNTAppFolder(RepoGenBaseFolder parentFolder) :
                    base("MXNT", "/contextmenu[@processname='MXNT']", parentFolder, 30000, null, false, "055b2bb7-7b00-41c2-b9f4-d9ab2b2177ac", "")
            {
                _aboutmeasurexInfo = new RepoItemInfo(this, "AboutMeasureX", "?/?/menuitem[@accessiblename='About Measure-X...']", 30000, null, "01ecffe6-102d-4bcb-9c8b-8c5a4903d35d");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("055b2bb7-7b00-41c2-b9f4-d9ab2b2177ac")]
            public virtual Ranorex.ContextMenu Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.ContextMenu>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("055b2bb7-7b00-41c2-b9f4-d9ab2b2177ac")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The AboutMeasureX item.
            /// </summary>
            [RepositoryItem("01ecffe6-102d-4bcb-9c8b-8c5a4903d35d")]
            public virtual Ranorex.MenuItem AboutMeasureX
            {
                get
                {
                    return _aboutmeasurexInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The AboutMeasureX item info.
            /// </summary>
            [RepositoryItemInfo("01ecffe6-102d-4bcb-9c8b-8c5a4903d35d")]
            public virtual RepoItemInfo AboutMeasureXInfo
            {
                get
                {
                    return _aboutmeasurexInfo;
                }
            }
        }

        /// <summary>
        /// The AboutMeasureXAppFolder folder.
        /// </summary>
        [RepositoryFolder("55bdea48-1aa7-4b42-bbed-26811b04a58e")]
        public partial class AboutMeasureXAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _text1928Info;

            /// <summary>
            /// Creates a new AboutMeasureX  folder.
            /// </summary>
            public AboutMeasureXAppFolder(RepoGenBaseFolder parentFolder) :
                    base("AboutMeasureX", "/form[@title='About Measure-X']", parentFolder, 30000, null, true, "55bdea48-1aa7-4b42-bbed-26811b04a58e", "")
            {
                _text1928Info = new RepoItemInfo(this, "Text1928", "text[@controlid='1928']", 30000, null, "f64c0422-bff5-4d5b-8acb-4d233fad4d72");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("55bdea48-1aa7-4b42-bbed-26811b04a58e")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("55bdea48-1aa7-4b42-bbed-26811b04a58e")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Text1928 item.
            /// </summary>
            [RepositoryItem("f64c0422-bff5-4d5b-8acb-4d233fad4d72")]
            public virtual Ranorex.Text Text1928
            {
                get
                {
                    return _text1928Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text1928 item info.
            /// </summary>
            [RepositoryItemInfo("f64c0422-bff5-4d5b-8acb-4d233fad4d72")]
            public virtual RepoItemInfo Text1928Info
            {
                get
                {
                    return _text1928Info;
                }
            }
        }

    }
#pragma warning restore 0436
}