///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;
using static PTB_Verification.PTB_VerificationRepositoryFolders;

namespace PTB_Verification
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Verification recording.
    /// </summary>
    [TestModule("e047619c-5128-47d0-ba2c-b322c91ad192", ModuleType.Recording, 1)]
    public partial class Verification : ITestModule
    {
        /// <summary>
        /// Holds an instance of the PTB_VerificationRepository repository.
        /// </summary>
        public static PTB_VerificationRepository repo = PTB_VerificationRepository.Instance;

        static Verification instance = new Verification();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Verification()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Verification Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.0")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        public Excel.Workbook workBook = null;

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.0")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 500;
            Keyboard.DefaultKeyPressTime = 200;
            Delay.SpeedFactor = 1.00;

            Init();
                       
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='0.0000000000') on item 'ExcelPTBResultsTable.CellM4'.", repo.ExcelPTBResultsTable.CellM4Info, new RecordItemIndex(0));
            Validate.Attribute(repo.ExcelPTBResultsTable.CellM4Info, "Text", "0.0000000000");
            Delay.Milliseconds(100);

            

            





        }

        #region Image Feature Data
        #endregion
    }
#pragma warning restore 0436
}
